### ISSUE TITLE
Compute type usability and bugs

### ISSUE THREAD

**Issue by ellisonbg** [jupyter-server/jupyter-scheduler#177]
## Description

We have found a number of usability issues/bugs related to the compute type dropdown:

- [ ]  It doesn't have a default value. At a minimum, we should select the first compute type value provided by the environment and use that as the default selection. (#187)
- [ ]  If there isn't a compute type selected, the user isn't warned that is an error. (should be obsoleted by PR above)
- [x]  ~~We may want to enable an environment to provide a default compute type along with the list of supported compute type values.~~ (#188)
- [x]  When there are many compute types, the dropdown occupies too much vertical space, which covers the "Compute type" label. (#183)
- [ ]  Rerunning a job doesn't fill in the previous compute type used. (#187)

## Context

- Version: 0.5.1

**Comment by jweill-aws** [comment]
Compute type with no max-height:

![image](https://user-images.githubusercontent.com/93281816/197309630-236a45ba-e870-4a5a-87e2-a993b1083664.png)


Compute type with a `20em` max-height:

![image](https://user-images.githubusercontent.com/93281816/197309567-c36e8736-4870-4980-b538-2dead6ff4635.png)

**Comment by jweill-aws** [comment]
We at least intend to select the first compute type when an environment is changed:

https://github.com/jupyter-server/jupyter-scheduler/blob/15ad1c133286be96a2015a61316b857830350245/src/mainviews/create-job.tsx#L161-L168

**Comment by jweill-aws** [comment]
> It doesn't have a default value. At a minimum, we should select the first compute type value provided by the environment and use that as the default selection.

This works when there are multiple environments, each with one or more compute types: we select the first compute type.

It seems to fail when there is one environment with one or more compute type, and that environment becomes seleected automatically. This is SageMaker's use case.

**Comment by jweill-aws** [comment]
The third item in the OP above is an enhancement, not a bug, so I filed it as #188.
